project:
  type: book
  output-dir: docs
  resources: images/_icons/

book:
  title: "Introducción a la Programación II"
  author: "Paola Corrales y Yanina Bellini Saibene"
  doi: https://doi.org10.5281/zenodo.14288649
  language: "ES"
  repo-url: "https://github.com/rse-r/intro-programacion"
  chapters:
    - index.qmd
    - 00_intro.qmd
    - 01_proyectos.qmd
    - 02_lectura.qmd
    - 03_manipulacion-1.qmd
    - 04_git-1.qmd
    - 05_graficos.qmd
    - 06_manipulacion-2.qmd
    - 07_funciones.qmd
    - 08_git-2.qmd
    - 09_paquetes-1.qmd
    - 10_documentacion.qmd
    - 11_errores.qmd
    - 12_contribuir.qmd
    - references.qmd
  appendices:
    - A_instalacion.qmd
    - B_config_pk.qmd
    - C_soluciones.qmd
    - D_checklist.qmd
  sidebar:
    background: "#916699"
    search: true
    
bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, style.scss]
    code-link: true
    mainfont: Noto Sans
    monofont: Source Code Pro
    author-meta: "Yanina Bellini Saibene y Paola Corrales"
  pdf:
    documentclass: scrreprt



